### ISSUE TITLE
getting  error when installing

### ISSUE THREAD

**Issue by Benjamin-FC** [magarcia/generator-angular2-webpack-starter#1]
D:\Temp_delete_delete>npm install -g  angular2-webpack-starter
npm ERR! addLocal Could not install C:\Users\Admin\AppData\Roaming\npm\node_modules\angular2-webpack-starter\examples_fixed_cjs_http
npm WARN install Couldn't install optional dependency: ENOENT: no such file or directory, open 'C:\Users\Admin\AppData\Roaming\npm\node_modules\angular2-webpack-starter
\examples_fixed_cjs_http'

**Comment by magarcia** [comment]
Ups, I had an error in documentation, you should install:
`npm install -g generator-angular2-webpack-starter`

**Comment by magarcia** [comment]
Fixed in https://github.com/magarcia/generator-angular2-webpack-starter/commit/7822218a5cf87921ed39bfaa237e57bf12cab564
