### ISSUE TITLE
<footer> error

### ISSUE THREAD

**Issue by Benjamin-FC** [magarcia/generator-angular2-webpack-starter#2]
App.ts:
My generated footer looks like this and failed to load.  
 <footer>
      ng-2-yo by Jenny R xxx@xxx.com
    </footer>

ORIGINAL EXCEPTION: Template parse errors:
Unexpected closing tag "footer" ("
    <footer>
      ng-2-yo by Jenny R xxx@xxx.com
    [ERROR ->]</footer>
  "): App@21:4

**Comment by amilajack** [comment]
I got the same error:

<img width="707" alt="screen shot 2016-01-22 at 1 30 28 pm" src="https://cloud.githubusercontent.com/assets/6374832/12523545/68540746-c10c-11e5-993b-9218b03ae13a.png">

**Comment by magarcia** [comment]
Fixed with version 0.0.3.

@jennyraj @amilajack Thanks for reporting
